name: Build

on:
  push:
    branches: [ testing-prototype ]
  pull_request:
    branches: [ testing-prototype ]

jobs:
################################################################################
  Build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tests

    steps:
    - uses: actions/checkout@v1
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - name: Install lcov
      run: sudo apt-get install lcov
    - name: execute which lcov
      run: which lcov
#     - name: build euler1D-VL
#       working-directory: ./euler1D-VL/
#       run: make
#     - name: Build tests
#       run: make
#     - name: Run tests
#       run: ./Tests.exe
################################################################################
