name: C/C++ CI

on:
  push:
    branches: [ testing-prototype ]
  pull_request:
    branches: [ testing-prototype ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tests

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run-tests
      run: ./Tests.exe
