name: C/C++ CI

on:
  push:
    branches: [ testing-prototype ]
  pull_request:
    branches: [ testing-prototype ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tests

    steps:
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - uses: actions/checkout@v1
    - name: make
      run: make
#    - name: run test
#      run: ./Tests.exe
